<?php

/**
 * @file
 * Module to make search to library database
 * and showing the result in Drupal page.
 *
 * Last modified: 13.03.2013 Mika Hatakka
 */
// TODO libdbsearch sivujen alta tehty sivustohaku aiheuttaa WSOD:n.    7.3.2013 MHa

/**
 * Implements hook_help().
 */
function libdbsearch_help($path, $arg) {
  if ($path == 'admin/help#libdbsearch') {
    return check_markup(file_get_contents(dirname(__FILE__) . "/README.txt"));
  }
}

/**
 * Implemtents hook_menu().
 */
function libdbsearch_menu() {
  $items = array();
  $items['admin/config/search/libdbsearch'] = array(
    'title' => 'Library database',
    'description' => 'Description',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('libdbsearch_admin'),
    'access arguments' => array('administer library search'),
    'file' => 'libdbsearch.admin.inc',
  );
  $items['admin/config/search/libdbsearch/general'] = array(
    'title' => 'General settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['libdbsearch'] = array(
    'title' => 'Library database search',
    'page callback' => 'libdbsearch_view',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function libdbsearch_permission() {
  return array(
    'administer library search' => array(
      'title' => t('Administer library database search'),
    ),
  );
}

function libdbsearch_view($action = 'empty', $keys = '') {
  if (!isset($_POST['form_id'])) {

    if ($action == 'empty') {
      return 'Ohjeita haun tekemiseen.';
    }
//    dpm($keys, 'keys');
//    dpm($action, 'action');
//    dpm($_GET, 'GET');
//    watchdog(7, 'Form send');



    $origo = new LibdbConnection();
    $origo->init($action, $keys);
    $result = $origo->askPage();

//    dpm($result, 'result');

    if (empty($result)) {
      $output = 'Internal Function Error.';
    }
    else {
      $output = '';
      $parser = new OrigoParser($result, $action);
      $something = $parser->constructXML();

//      dpm($something);

      $xml = str_replace(
          array('&nbsp;', '&auml;', '&amp;#228;'), array(' ', 'ä', 'ä'), $something);

      $ret = json_decode(json_encode((array) simplexml_load_string($xml)), 1);
      dpm($ret, 'result array');

      if (isset($ret['Otsikko'])) {
        if (isset($ret['Otsikko']['Linkki']['Losoite'])) {
          drupal_set_title(_libdbsearch_extract_link($ret['Otsikko']['Linkki']), PASS_THROUGH);
        }
        else {
          drupal_set_title($ret['Otsikko']);
        }

        if (isset($ret['Virhe'])) {
          if (isset($ret['Teksti'][1]) && $ret['Teksti'][1] == 'No results') {
            $output .= t('Your search yielded no results');
          }
          else {
            $output .= t('Error performing the search.');
          }
        }
        else {
          $f = 'libdbsearch_set_' . $action . '_data';
          if (function_exists($f)) {
            $output .= $f($ret);
          }
          else {
            $output .= 'Unknown function ' . $f . '<br />';
          }
        }
      }
    }

    return $output;
  }
//  dpm($_GET, 'GET');
//  dpm($_POST, 'POST');
//  watchdog(7, 'The other');
  return '';
}

//-----------------------------------------------
// Libdbsearch Origo page wrappers.

/**
 * Page for search result list.
 * 
 * @param type $data
 * @return type
 */
function libdbsearch_set_haku_data($data) {
  $output = '';
  if (isset($data['Hakuinfo']['Teksti'])) {
    if (is_array($data['Hakuinfo']['Teksti'])) {
      foreach ($data['Hakuinfo']['Teksti'] as $val) {
//        dpm($val, 'check_plain');
        $output .= check_plain($val) . '<br />';
      }
    }
    else {
//      dpm($data['Hakuinfo']['Teksti'], 'check_plain');
      $output .= check_plain($data['Hakuinfo']['Teksti']) . '<br />';
    }
  }

  $info = _libdbsearch_add_info($data);
//  dpm($info);
  if (count($info) > 0) {
    $output .= $info[0];
  }

  $navigation = _libdbsearch_add_navi($data);
  if (count($navigation) > 0) {
    $output .= $navigation[0];
  }

  $header = array();
  $rows = array();
  $hdr = FALSE;
  if (isset($data['Hakutulos'])) {
    if (isset($data['Hakutulos']['Selausotsikot']['Totsikko'])) {
      foreach ($data['Hakutulos']['Selausotsikot']['Totsikko'] as $value) {
        $header[] = _libdbsearch_extract_text($value);
      }
    }
    if (isset($data['Hakutulos']['Selauslista']['Teos'])) {
      foreach ($data['Hakutulos']['Selauslista']['Teos'] as $value) {
        $row = array();
        foreach ($value as $val) {
          $row[] = _libdbsearch_extract_value($val);
        }
        $rows[] = $row;
      }
    }
    if (isset($data['Hakutulos']['Aineistolajittain']['Aineistolaji'])) {
      foreach ($data['Hakutulos']['Aineistolajittain'] as $key => $value) {
        $row = array();
        foreach ($value as $key => $val) {
          if ($hdr == FALSE) {
//            dpm($key, 'check_plain');
            $header[] = check_plain($key);
          }
          $row[] = _libdbsearch_extract_value($val);
        }
        $rows[] = $row;
        $hdr = TRUE;
      }
    }
  }

  $output .= theme('table', array('header' => $header, 'rows' => $rows));

  if (count($info) > 1) {
    $output .= $info[1];
  }

  if (count($navigation) > 1) {
    $output .= $navigation[1];
  }

  return $output;
}

function libdbsearch_set_selauslista_data($data) {
  return libdbsearch_set_haku_data($data);
}

function libdbsearch_set_teos_data($data) {
  $output = '';

  $info = _libdbsearch_add_info($data);
//  dpm($info);

  $navigation = _libdbsearch_add_navi($data);
  if (count($navigation) > 0) {
    $output .= $navigation[0];
  }


  if (isset($data['Teostiedot']['Rivi'])) {
    $output .= _libdbsearch_create_work_table($data['Teostiedot']['Rivi']);
  }

  if (isset($data['Kuva'])) {
    $image = array(
      'path' => $data['Kuva'],
      'width' => 100,
//      'height' => 50,
      'alt' => 'Teoksen kansikuva',
//      'title' => '',
      'attributes' => array('class' => 'work_pic'),
    );
    $output .= theme('image', $image);
  }

  if (isset($info['Tarkat tiedot'])) {
    $output .= $info['Tarkat tiedot'];
    unset($info['Tarkat tiedot']);
  }

  if (isset($info['Näytä sisältö / kappaleet'])) {
    $output .= $info['Näytä sisältö / kappaleet'];
    unset($info['Näytä sisältö / kappaleet']);
  }

  if (isset($info['Esittelyteksti'])) {
    $output .= $info['Esittelyteksti'];
    unset($info['Esittelyteksti']);
  }

  if (isset($data['Valitun_saatavuus'])) {
    $output .= _libdbsearch_availability_table($data['Valitun_saatavuus']);
  }

  if (isset($data['Saatavuus'])) {
    $output .= _libdbsearch_availability_table($data['Saatavuus']);
  }

  foreach ($info as $value) {
    if (empty($value)) {
      continue;
    }
    $output .= $value;
  }
  return $output;
}

function libdbsearch_set_osakohteet_data($data) {
  $output = '';
  $header = array();
  $rows = array();

  if (isset($data['Teksti'])) {
    if (isset($data['Teksti'][0])) {
      foreach ($data['Teksti'] as $value) {
        if (empty($value)) {
          continue;
        }
//        dpm($value, 'check_plain');
        $output .= check_plain($value) . '<br />';
      }
    }
    else {
//      dpm($data['Teksti'], 'check_plain');
      $output .= check_plain($data['Teksti']) . '<br />';
    }
  }

  if (isset($data['Osakohteet'])) {
    if (isset($data['Osakohteet']['Totsikot']['Totsikko'])) {
      foreach ($data['Osakohteet']['Totsikot']['Totsikko'] as $value) {
        $header[] = _libdbsearch_extract_text($value);
      }
    }
    if (isset($data['Osakohteet']['Rivi'])) {
      foreach ($data['Osakohteet']['Rivi'] as $value) {
        $row = array();
        foreach ($value as $val) {
          $row[] = _libdbsearch_extract_value($val);
        }
        $rows[] = $row;
      }
    }
  }

  $output .= theme('table', array('header' => $header, 'rows' => $rows));

  $info = _libdbsearch_add_info($data);

  $navigation = _libdbsearch_add_navi($data);

  if (isset($navigation[0])) {
    $output .= $navigation[0];
  }
  if (isset($info[0])) {
    $output .= $info[0];
  }

  return $output;
}

//-----------------------------------------------
// Libdbsearch common helper functions.

/**
 * Prints out text or link from section.
 * 
 * @param type $value
 * @return type
 */
function _libdbsearch_extract_text($value) {
  $output = '';
  if (isset($value['Teksti'])) {

    if (is_array($value['Teksti'])) {
      foreach ($value['Teksti'] as $str) {
        $output .= $str . '<br />';
      }
    }
    else {
      $output = $value['Teksti'];
    }
  }
  elseif (isset($value['Linkki'])) {
    $output = _libdbsearch_extract_link($value['Linkki']);
  }

  return $output;
}

function _libdbsearch_extract_link($link) {
  if (isset($link['Lnewwnd']) && strtoupper($link['Lnewwnd']) == 'TRUE') {
    if (strpos($link['Losoite'], 'http://') === FALSE) {
      $linkki = variable_get('libdb_server', '') . $link['Losoite'];
    }
    else {
      $linkki = $link['Losoite'];
    }
  }
  else {
    $linkki = str_replace('.asp?', '/', $link['Losoite']);
    $linkki = 'libdbsearch/' . $linkki;
  }
  $output = l($link['Lteksti'], $linkki);
  if (isset($link['Lextrateksti'])) {
    $output .= $link['Lextrateksti'];
  }
  return $output;
}

/**
 * Prints out text or link from two level section.
 * 
 * @param type $value
 * @return type
 */
function _libdbsearch_extract_value($value) {
  if (is_array($value)) {
    return _libdbsearch_extract_text($value);
  }
  else {
    return $value;
  }
}

/**
 * Create's page navigation .
 * 
 * @param type $data
 * @return type
 */
function _libdbsearch_add_navi($data) {
  $output = array();

  if (isset($data['Navigointi'])) {
    foreach ($data['Navigointi'] as $val) {
      $out_navi = '';
      if (isset($val['Teksti'])) {
        $out_navi .= $val['Teksti'];
      }
      if (isset($val['Valinta'])) {
        foreach ($val['Valinta'] as $value) {
          $out_navi .= _libdbsearch_extract_navi_text($value);
        }
      }
      if (isset($val['Haettu'])) {
        $out_navi .= _libdbsearch_extract_navi_text($val['Haettu']);
      }
      $output[] = $out_navi;
    }
  }
  return $output;
}

/**
 * Extracts one navigation component.
 * 
 * @param type $data
 * @return string
 */
function _libdbsearch_extract_navi_text($data) {
  $output = '';
  if (is_array($data)) {
    if (isset($data['@attributes']['separator'])) {
      if ($data['@attributes']['separator'] == 'yes') {
        $output .= ' | ';
      }
    }
    if (isset($data['Haettu'])) {
      $output .= $data['Haettu'] . ' ';
    }
    if (isset($data['Linkki'])) {
      $output .= _libdbsearch_extract_text($data) . ' ';
    }
  }
  else {
    $output .= $data . ' ';
  }
  return $output;
}

/**
 * Create's section info data
 * 
 * @param type $data
 * @return string
 */
function _libdbsearch_add_info($data) {
  $output = array();
  $cnt = 0;

  if (isset($data['Lohko'])) {
    if (isset($data['Lohko'][0])) {
      foreach ($data['Lohko'] as $val) {
        $out_info = '';
        $idx = $cnt;
        if (isset($val['Teksti'])) {
          $out_info .= _libdbsearch_extract_text($val);
        }
        if (isset($val['Linkki'])) {
          $out_info .= _libdbsearch_extract_text($val);
          $idx = $val['Linkki']['Lteksti'];
        }
        if (!empty($out_info)) {
          $out_info .= '<br />';
        }
        $output[$idx] = $out_info;
        $cnt++;
      }
    }
    else {
      $output[] = _libdbsearch_extract_text($data['Lohko']);
    }
  }

  return $output;
}

function _libdbsearch_create_work_table($data) {
  $header = array();
  $rows = array();

  foreach ($data as $value) {
    $row = array();
    $row[] = isset($value['Selite']) ? $value['Selite'] : '';

    if (isset($value['Tieto'][0])) {
      $str = '';
      foreach ($value['Tieto'] as $val) {
        $str .= _libdbsearch_extract_value($val) . '<br />';
      }
    }
    else {
      $str = isset($value['Tieto']) ? _libdbsearch_extract_value($value['Tieto']) : '';
    }
    $row[] = $str;

    $rows[] = $row;
  }

  return theme('table', array('header' => $header, 'rows' => $rows));
}

function _libdbsearch_availability_table($data) {
  $output = '';
  $header = array();
  $rows = array();
  $hdr = FALSE;

  if (isset($data['Valiotsikko'])) {
    $output .= '<h3>' . $data['Valiotsikko'] . '</h3>';
  }

  if (isset($data['Teksti'])) {
    $output .= $data['Teksti'];
  }

  if (isset($data['Teos'])) {
    foreach ($data['Teos'] as $val) {
      $row = array();
      foreach ($val as $key => $value) {
        if ($hdr == FALSE) {
          $header[] = $key;
        }
        if (is_array($value)) {
          $row[] = _libdbsearch_extract_text($value);
        }
        else {
          $row[] = $value;
        }
      }
      $hdr = TRUE;
      $rows[] = $row;
    }
    $output .= theme('table', array('header' => $header, 'rows' => $rows));
  }


  if (isset($data['Kirjasto'])) {
    if (isset($data['Kirjasto'][0])) {
      foreach ($data['Kirjasto'] as $lib) {
        _libdbsearch_make_avail_tablerows($lib, $header, $rows, $hdr);
        $hdr = TRUE;
      }
    }
    else {
      _libdbsearch_make_avail_tablerows($data['Kirjasto'], $header, $rows, $hdr);
    }
    $header[0] = t('Location');
    $output .= theme('table', array('header' => $header, 'rows' => $rows));
  }

  return $output;
}

function _libdbsearch_make_avail_tablerows($lib, &$header, &$rows, $hdr) {
  if (isset($lib['Kirjastonimi'])) {
    $rows[] = array(array('data' => $lib['Kirjastonimi'], 'colspan' => 7));
  }
  if (isset($lib['Sijainti'])) {
    $row = array();
    foreach ($lib['Sijainti'] as $key => $value) {
      if ($hdr == FALSE) {
        $header[] = $key;
      }
      if (is_array($value)) {
        $row[] = _libdbsearch_extract_text($value);
      }
      else {
        $row[] = $value;
      }
    }
    $rows[] = $row;
  }
}

//***************************************************************************
// Libdbsearch block
//

/**
 * Implements hook_block_info().
 */
function libdbsearch_block_info() {
  $blocks = array();

  $blocks['libdbsearch'] = array(
    'info' => t('Library datasystem search'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function libdbsearch_block_view($block_name = '') {
  if ($block_name == 'libdbsearch') {
    $block['title'] = t('Search');
    $block['content'] = drupal_get_form('libdbsearch_box');
    // Add extra information to the end of block.
//    $ext_par = variable_get('libdbsearch_extra_info', '');
//    if (!empty($ext_par)) {
//      $par = variable_get('libdbsearch_format', 0);
//      $block['content'] .= check_markup($ext_par, $par, FALSE);
//    }

    return $block;
  }
}

/**
 * Output a search form for the search block and the theme's search box.
 *
 * @see search_box_form_submit()
 * @see theme_search_box_form()
 */
function libdbsearch_box() {
  drupal_add_css(drupal_get_path('module', 'libdbsearch') . '/libdbsearch.css', 'module', 'all', FALSE);
  $swords = _libdbsearch_extract_pars();

  $form['vapaasana'] = array(
    '#title' => t('Search words'),
    '#type' => 'textfield',
    '#attributes' => array('title' => t("Give the word to search. " .
          "You can use AND, OR and NOT limit the results. You can break " .
          "the searchword with #-mark, to get all words that include given word.")),
    '#default_value' => isset($swords['vapaasana']) ? $swords['vapaasana'] : '',
  );

  $libraries = libdbsearch_read_list(1);
  $form['piste'] = array(
    '#type' => 'select',
    '#title' => t('Libraries'),
    '#default_value' => isset($swords['piste']) ? $swords['piste'] : '-',
    '#options' => $libraries,
  );

  $form['advanced'] = array(
    '#title' => t('Advanced search'),
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  $form['advanced']['aineistoittain'] = array(
    '#type' => 'checkbox',
    '#title' => t('Group by category'),
    '#default_value' => isset($swords['aineistoittain']) ? $swords['aineistoittain'] : 0,
  );
  $form['advanced']['uutuudet'] = array(
    '#type' => 'checkbox',
    '#title' => t('Novelties'),
    '#default_value' => isset($swords['uutuudet']) ? $swords['uutuudet'] : 0,
  );
  // osakohteet
  // hakujoukko
  $form['advanced']['tekija'] = array(
    '#title' => t('Author'),
    '#type' => 'textfield',
    '#default_value' => isset($swords['tekija']) ? $swords['tekija'] : '',
  );
  $form['advanced']['nimeke'] = array(
    '#title' => t('Work title'),
    '#type' => 'textfield',
    '#default_value' => isset($swords['nimeke']) ? $swords['nimeke'] : '',
  );
  $form['advanced']['asiasana'] = array(
    '#title' => t('Index terms / Subject'),
    '#type' => 'textfield',
    '#default_value' => isset($swords['asiasana']) ? $swords['asiasana'] : '',
  );
  $form['advanced']['tunnus'] = array(
    '#title' => t('ISBN / Number'),
    '#type' => 'textfield',
    '#default_value' => isset($swords['tunnus']) ? $swords['tunnus'] : '',
  );
  $form['advanced']['sarja'] = array(
    '#title' => t('Series'),
    '#type' => 'textfield',
    '#default_value' => isset($swords['sarja']) ? $swords['sarja'] : '',
  );
  $form['advanced']['kustantaja'] = array(
    '#title' => t('Publisher'),
    '#type' => 'textfield',
    '#default_value' => isset($swords['kustantaja']) ? $swords['kustantaja'] : '',
  );
  $work_class = libdbsearch_read_list(2);
  $form['advanced']['advanced']['luokkaryhma'] = array(
    '#type' => 'select',
    '#title' => t('Class'),
    '#default_value' => !empty($swords['luokkaryhma']) ? $swords['luokkaryhma'] : '-',
    '#options' => $work_class,
  );
  $form['advanced']['julkaisuaika'] = array(
    '#title' => t('Year'),
    '#type' => 'textfield',
    '#default_value' => isset($swords['julkaisuaika']) ? $swords['julkaisuaika'] : '',
    '#maxlength' => 11,
    '#size' => 9,
  );
  $work_lang = libdbsearch_read_list(3);
  $form['advanced']['kieliryhma'] = array(
    '#type' => 'select',
    '#title' => t('Language'),
    '#default_value' => isset($swords['kieliryhma']) ? $swords['kieliryhma'] : '-',
    '#options' => $work_lang,
  );
  $work_material = libdbsearch_read_list(4);
  $form['advanced']['materiaaliryhma'] = array(
    '#type' => 'select',
    '#title' => t('Material'),
    '#default_value' => isset($swords['materiaaliryhma']) ? $swords['materiaaliryhma'] : '-',
    '#options' => $work_material,
  );
  $work_departments = libdbsearch_read_list(5);
  $form['advanced']['osastoryhma'] = array(
    '#type' => 'select',
    '#title' => t('Departments'),
    '#default_value' => isset($swords['osastoryhma']) ? $swords['osastoryhma'] : '-',
    '#options' => $work_departments,
  );
  // arvostelut
  // arvostelunteksti

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
    '#submit' => array('libdbsearch_box_submit'),
  );
  $form['clear'] = array(
    '#type' => 'submit',
    '#value' => t('Clear'),
    '#submit' => array('libdbsearch_box_submit'),
  );
//  $form['#submit'][] = 'libdbsearch_block_form_submit';

  return $form;
}

// TODO avaimien käsittely ei kuulu tähän moduuliin,
// vaan origo moduuliin!!!
// 
// Tämä on yleinen moduuli, joka saa järjestelmä kohtaisen 
// avun järjestelmäkohtaislta moduuleilta.  MHa 8.8.2011
//

function libdbsearch_box_submit($form, &$form_state) {
  if ($form_state['values']['op'] == $form_state['values']['submit']) {
    $type = empty($form_state['values']['module']) ? 'haku' : $form_state['values']['module'];
    $params = _libdbsearch_parse_keys($form_state['values']);
//    dpm($params);
    $form_state['redirect'] = 'libdbsearch/' . $type . '/' . $params;
  }
  else { // Clear
    $form_state['redirect'] = 'libdbsearch';
  }
}

/**
 * Extract search words from URL address to textboxes.
 * 
 * @return type
 */
function _libdbsearch_extract_pars() {
  $swords = array();
  $args = arg();
  if (isset($args[2])) {
    $params = explode('&', $args[2]);
    foreach ($params as $val) {
      $param = explode('=', $val);
      if (count($param) == 2) {
        $swords[$param[0]] = $param[1];
      }
      elseif (count($params) == 1 && count($param) == 1) {
        $swords['vapaasana'] = $param[0];
      }
    }
  }
  return $swords;
}

/**
 * Converts key array to key pairs that can be added to address line.
 *
 * @param array $list searchkey array
 * @return string used search key pairs in parameter string
 */
function _libdbsearch_parse_keys($list) {
  $tags = array(
    'vapaasana', 'piste', 'aineistoittain', 'uutuudet', 'tekija', 'nimeke',
    'asiasana', 'tunnus', 'sarja', 'kustantaja', 'luokkaryhma', 'julkaisuaika',
    'kieliryhma', 'materiaaliryhma', 'osastoryhma',
  );

  if ($list == NULL) {
    return NULL;
  }
  $ret_list = '';
  foreach ($list as $key => $val) {
    if (empty($val) || !in_array($key, $tags)) {
      continue;
    }
    if (!empty($ret_list)) {
      $ret_list .= '&';
    }
    $ret_list .= $key . '=' . $val;
    if (strtolower($key) == 'op') {
      break;
    }
  }
  return $ret_list;
}

//
// End Of Block part
//****************************************************************************

/**
 * Get one of the lists in database to use in dropdown select.
 *
 * @param integer $sel type of list
 * @return array chosen list array
 */
function libdbsearch_read_list($list) {
  $ret = FALSE;
  $result = db_query('SELECT arvo, teksti FROM {libdbsearch_lists} 
    WHERE tyyppi = :tyyppi ORDER BY nro', array(':tyyppi' => $list));
  foreach ($result as $record) {
    $ret[$record->arvo] = $record->teksti;
  }
  if ($ret === FALSE) {
    $ret = array('' => '-');
  }
  return $ret;
}

/**
 * Implemtents hook_cron().
 */
function libdbsearch_cron() {
// Check lists every Sunday after 3 in the morning.
//  if ((date('w') == 0) && (date('G') > 3) &&
//      variable_get('libdbsearch_lists_updated', 0) < (time() - 'LIST_UPDATE_PERIOD')) {
//    $origo_upd = new LibdbUpdate();
//    $origo_upd->origoUpdateLists();
//    variable_set('libdbsearch_lists_updated', time());
//  }
}
