<?php
// $Id:

/**
 * @file
 * Language extraction table for finnish to english base translation.
 *
 * Last modified: 18.04.2013 Mika Hatakka
 */

    $lista = array(
        "Aineistolaji" => "Material",
        "Aineiston_sijainti" => "Location of the material",
        "Aineiston_yleismaare" => "Material's generic attribute",
        "Alkuperainen_kieli" => "Original language",
        "Alkuperaisjulkaisu" => "Original publication",
        "Alkuteos" => "Original title",
        "Asiasanat_/_Aihe" => "Index terms / Subject",
        "EAN-luokka" => "EAN code",
        "Edellinen" => "Previous",
        "Edellinen_teos" => "Previous work",
        "Esittajahuomautus" => "Artist notification",
        "Esittelyteksti" => "Introduction",
        "Huomautus" => "Remark",
        "Ikaraja" => "Age limit",
        "Ilmestymistiheys" => "Frequency of publication",
        "ISBN" => "ISBN",
        "ISMN" => "ISMN",
        "ISSN" => "ISSN",
        "Julkaisutiedot" => "Publication information",
        "Luokka" => "Class",
        "Mittakaava" => "Scale",
        "Muut_kielet" => "Other languages",
        "Muut_nimekkeet" => "Other titles",
        "Muut_tekijat" => "Other authors",
        "Nimi" => "Name",
        "Numerointi" => "Numbering",
        "Nayta_kaikki" => "Show all",
        "Nayta_sisalto_/_kappaleet" => "See contents / songs",
        "Osa" => "Part",
        "Painos" => "Edition",
        "Paakielet" => "Main language",
        "Saatavuustiedot" => "Availability information",
        "Saatavuustiedot_muissa_kirjastoissa" => "Availability in other libraries",
        "Sarja" => "Series",
        "Selauslistalle" => "To search list",
        "Seuraava" => "Next",
        "Seuraava_teos" => "Next work",
        "Sijaintitiedot" => "Location information",
        "Sisalto" => "Contents",
        "Sivu:_" => "Page: ",
        "Soittimet" => "Instruments",
        "Tarkat_tiedot" => "Detailed information",
        "Tekija" => "Author",
        "Tekija_/_esittaja" => "Author / performer",
        "Teoksen_nimi" => "Work title",
        "Tuotetunnus" => "Product code",
        "UDK-luokka" => "UDK class",
        "Ulkoasu" => "Appearance",
        "Vaitoskirjahuomautus" => "Dissertation notification",
        "Valmistumisvuosi" => "Year of production",
        "Varaa_teos" => "Place a hold",
        "Vuosi" => "Year",
        "Yhtenaistetty_nimeke" => "Uniform title",
        "YKL-luokka" => "YKL class",
        "Aanitys/kuvaus" => "Recording/filming",
        "Kouvolan_kaupunginkirjasto" => "Kouvola libraries",
        "Kotkan_kaupunginkirjasto" => "Kotka libraries",
        "Haminan_kaupunginkirjasto" => "Hamina libraries",
        "Pyhtaan_kunnankirjasto" => "Pyhtää library",
        "Iitin_kunnankirjasto" => "Iitti library",
        "Miehikkalan_kunnankirjasto" => "Miehikkälä library",
        "Virolahden_kunnankirjasto" => "Virolahti library",
    );
?>
