<?php

// $Id$

/**
 * @file
 * Module to make search to library database
 * and showing the result in Drupal page.
 *
 * Last modified: 10.05.2011 Mika Hatakka
 */

/**
 *
 * @return string 
 */
function libdb_test_libsearch() {
  $result['search'] = array(
    'template' => 'table',
    'title' => 'Haun tulos',
    'info' => array(
      'Teoksia löytyi yhteensä 64 kappaletta.',
      'Teokset 1 - 20',
    ),
    'navigation' => array(
      'Sivu: ',
      'Edellinen',
      array(
        'selected' => '1'
      ),
      array(
        'link' => array(
          'address' => 'selauslista.asp?edhaku=1&amp;lkm=64&amp;sivu=2&amp;lajittelu=1&amp;edlajittelu=1',
          'description' => '2',
        ),
      ),
      array(
        'link' => array(
          'address' => 'selauslista.asp?edhaku=1&amp;lkm=64&amp;sivu=3&amp;lajittelu=1&amp;edlajittelu=1',
          'description' => '3',
        ),
      ),
      array(
        'link' => array(
          'address' => 'selauslista.asp?edhaku=1&amp;lkm=64&amp;sivu=4&amp;lajittelu=1&amp;edlajittelu=1',
          'description' => '4',
        ),
      ),
      array(
        'link' => array(
          'address' => 'selauslista.asp?edhaku=1&amp;lkm=64&amp;sivu=2&amp;lajittelu=1&amp;edlajittelu=1',
          'description' => 'Seuraava',
        ),
      ),
    ),
    'result' => array(
      'headers' => array(
        'Tekijä',
        array(
          'link' => array(
            'address' => 'selauslista.asp?edhaku=1&amp;lkm=64&amp;lajittelu=2&amp;edlajittelu=1&amp;sivu=1',
            'description' => 'Teoksen nimi',
          ),
        ),
        array(
          'link' => array(
            'address' => 'selauslista.asp?edhaku=1&amp;lkm=64&amp;lajittelu=6&amp;edlajittelu=1&amp;sivu=1',
            'description' => 'Aineistolaji',
          ),
        ),
        array(
          'link' => array(
            'address' => 'selauslista.asp?edhaku=1&amp;lkm=64&amp;lajittelu=5&amp;edlajittelu=1&amp;sivu=1',
            'description' => 'Vuosi',
          ),
        ),
        array(
          'link' => array(
            'address' => 'selauslista.asp?edhaku=1&amp;lkm=64&amp;lajittelu=4&amp;edlajittelu=1&amp;sivu=1',
            'description' => 'Luokka',
          ),
        ),
//        'count' => '5',
      ),
      'rows' => array(
        array(
          'Ball, Bill',
          array(
            'link' => array(
              'address' => 'teos.asp?teosid=E3EBD947%2DF8A3%2D4106%2DA943%2D56DEF198160E&amp;listalta=1&amp;lkm=64&amp;lajittelu=1&amp;edhaku=1',
              'description' => 'Red Hat Linux trainer',
            ),
          ),
          'Kirja',
          '1999',
          '61.4',
        ),
        array(
          'Ball, Bill',
          array(
            'link' => array(
              'address' => 'teos.asp?teosid=0309D166%2D39FA%2D47FD%2DA379%2DDEF022E73867&amp;listalta=1&amp;lkm=64&amp;lajittelu=1&amp;edhaku=1',
              'description' => 'Red Hat Linux trainer',
            ),
          ),
          'Kirja',
          '1998',
          '61.4',
        ),
        array(
          'Barkakati, Naba',
          array(
            'link' => array(
              'address' => 'teos.asp?teosid=5DD051BC%2D5122%2D4067%2DAD3D%2DE9DB8742011A&amp;listalta=1&amp;lkm=64&amp;lajittelu=1&amp;edhaku=1',
              'description' => 'Red Hat Linux',
            ),
          ),
          'Kirja',
          '2000',
          '61.4',
        ),
        array(
          '&nbsp;',
          array(
            'link' => array(
              'address' => 'teos.asp?teosid=D33BB2C9%2DC94A%2D4BC7%2DBEDC%2D50292BFAC833&amp;listalta=1&amp;lkm=64&amp;lajittelu=1&amp;edhaku=1',
              'description' => 'Best Linux games : 1',
            ),
          ),
          'CD-ROM',
          'C1999',
          '79.81',
        ),
        array(
          '&nbsp;',
          array(
            'link' => array(
              'address' => 'teos.asp?teosid=A460CCB0%2DFCB2%2D4216%2DA41C%2DD0E94AE349C5&amp;listalta=1&amp;lkm=64&amp;lajittelu=1&amp;edhaku=1',
              'description' => 'Best Linux käyttöjärjestelmä 5.3 : compact',
            ),
          ),
          'CD-ROM',
          'c1999',
          '61.4',
        ),
        array(
          '&nbsp;',
          array(
            'link' => array(
              'address' => 'teos.asp?teosid=609881A1%2D89B6%2D453F%2D95D8%2D61D493588961&amp;listalta=1&amp;lkm=64&amp;lajittelu=1&amp;edhaku=1',
              'description' => 'The code : story of Linux',
            ),
          ),
          'DVD-levy',
          '[2005]',
          '61.4',
        ),
        array(
          'Durham, Jeff',
          array(
            'link' => array(
              'address' => 'teos.asp?teosid=E3F308C3%2D6738%2D49D5%2D9079%2D9736964DCF12&amp;listalta=1&amp;lkm=64&amp;lajittelu=1&amp;edhaku=1',
              'description' => 'Linux+ -sertifikaatti',
            ),
          ),
          'Kirja',
          '2002',
          '61.4',
        ),
        array(
          '&nbsp;',
          array(
            'link' => array(
              'address' => 'teos.asp?teosid=1AF77289%2D0F60%2D4723%2DA290%2DDFC746F7B057&amp;listalta=1&amp;lkm=64&amp;lajittelu=1&amp;edhaku=1',
              'description' => 'Edubuntu 7.10 for your PC &amp; server',
            ),
          ),
          'CD-ROM',
          '2007',
          '61.4',
        ),
        array(
          'Ek, Jesper',
          array(
            'link' => array(
              'address' => 'teos.asp?teosid=97302CA3%2D26BC%2D4554%2DA4F9%2D4727673D057C&amp;listalta=1&amp;lkm=64&amp;lajittelu=1&amp;edhaku=1',
              'description' => 'Linux internet-palvelimena',
            ),
          ),
          'Kirja',
          '2001',
          '61.72',
        ),
        array(
          'Gagne, Marcel',
          array(
            'link' => array(
              'address' => 'teos.asp?teosid=9BC0C8AC%2D2354%2D40A3%2D8C13%2D83337B4E513F&amp;listalta=1&amp;lkm=64&amp;lajittelu=1&amp;edhaku=1',
              'description' => 'Linux : järjestelmänhaltijan käsikirja',
            ),
          ),
          'Kirja',
          '2003',
          '61.4',
        ),
        array(
          'Gay, Warren W.',
          array(
            'link' => array(
              'address' => 'teos.asp?teosid=EADE44C4%2D111F%2D4E70%2DA937%2D8364D6F65413&amp;listalta=1&amp;lkm=64&amp;lajittelu=1&amp;edhaku=1',
              'description' => 'Linux-ohjelmointi trainer',
            ),
          ),
          'Kirja',
          '1999',
          '61.3',
        ),
        array(
          'Hakala, Viljo',
          array(
            'link' => array(
              'address' => 'teos.asp?teosid=4CC273DE%2D4B46%2D4A6B%2D8BBC%2D356ACF2891A6&amp;listalta=1&amp;lkm=64&amp;lajittelu=1&amp;edhaku=1',
              'description' => 'Linux, yrityksen avoin vaihtoehto',
            ),
          ),
          'Kirja',
          '1999',
          '61.4',
        ),
        array(
          'Hall, Jon',
          array(
            'link' => array(
              'address' => 'teos.asp?teosid=035C8362%2D168D%2D45C5%2D8283%2DBE9A0E8C098B&amp;listalta=1&amp;lkm=64&amp;lajittelu=1&amp;edhaku=1',
              'description' => 'Red Hat Linux keltanokille',
            ),
          ),
          'Kirja',
          '2000',
          '61.4',
        ),
        array(
          'Hedemalm, Gunvald',
          array(
            'link' => array(
              'address' => 'teos.asp?teosid=5D47EE67%2D2390%2D4F9B%2DA41B%2D0D7AB0F1E97D&amp;listalta=1&amp;lkm=64&amp;lajittelu=1&amp;edhaku=1',
              'description' => 'Linux-käsikirja',
            ),
          ),
          'Kirja',
          '2000',
          '61.4',
        ),
        array(
          'Hedemalm, Gunvald',
          array(
            'link' => array(
              'address' => 'teos.asp?teosid=EE4CAB67%2DD620%2D4AAB%2D84D6%2D0EEAD43F3DB6&amp;listalta=1&amp;lkm=64&amp;lajittelu=1&amp;edhaku=1',
              'description' => 'Linux-käsikirja',
            ),
          ),
          'Kirja',
          '1999',
          '61.4',
        ),
        array(
          'Hokkanen, Hannu',
          array(
            'link' => array(
              'address' => 'teos.asp?teosid=1AFE81C1%2D2813%2D494C%2DB5D4%2DF3EDA7A74931&amp;listalta=1&amp;lkm=64&amp;lajittelu=1&amp;edhaku=1',
              'description' => 'Linux ja Samba',
            ),
          ),
          'Kirja',
          '2000',
          '61.4',
        ),
        array(
          'Ingo, Henrik',
          array(
            'link' => array(
              'address' => 'teos.asp?teosid=19D1DCB1%2DA804%2D407A%2D9D88%2D07AB2013835A&amp;listalta=1&amp;lkm=64&amp;lajittelu=1&amp;edhaku=1',
              'description' => 'Avoin elämä : näin toimii Open Source',
            ),
          ),
          'Kirja',
          '2005',
          '61',
        ),
        array(
          'Jokinen, Ismo',
          array(
            'link' => array(
              'address' => 'teos.asp?teosid=09016B53%2D2ABC%2D42B1%2D91D7%2DD20F9FEBFD89&amp;listalta=1&amp;lkm=64&amp;lajittelu=1&amp;edhaku=1',
              'description' => 'Linux : peruskäyttäjän opas',
            ),
          ),
          'Kirja',
          '1999',
          '61.4',
        ),
        array(
          'Kannisto, Päivi',
          array(
            'link' => array(
              'address' => 'teos.asp?teosid=69436249%2D70F0%2D4B6E%2DA538%2DE7942E2B1C2F&amp;listalta=1&amp;lkm=64&amp;lajittelu=1&amp;edhaku=1',
              'description' => 'Platinainen pilvenreuna : Santeri Kanniston erokirja tietoyhteiskunnasta, yrittäjyydestä ja GNU/Linuxista',
            ),
          ),
          'Kirja',
          '2007',
          '99.16',
        ),
        array(
          'Kapanen, Timo',
          array(
            'link' => array(
              'address' => 'teos.asp?teosid=36A50A29%2DF008%2D4343%2D92E1%2DF3900E37BD23&amp;listalta=1&amp;lkm=64&amp;lajittelu=1&amp;edhaku=1',
              'description' => 'Linux-koulutuspaketti',
            ),
          ),
          'Kirja',
          '2004',
          '61.4',
        ),
      ),
    ),
    'notice' => array(
      'Teokset 1 - 20',
    ),
  );

  return $result;
}